import { GameData } from "@/types/game";

export const GAMES_DATA : GameData[] = [
  {
    id: 1,
    title: "Game1",
    rating: 7.5,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris. ",
    genre: "Genre 1",
    publisher: "Publisher 1",
    developer: "Developer 1",
    platform: "Platform 1",
  },
  {
    id: 2,
    title: "Game2",
    rating: 3.5,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 2",
    publisher: "Publisher 2",
    developer: "Developer 2",
    platform: "Platform 2",  
},
  {
    id: 3,
    title: "Game3",
    rating: 2.3,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 3",
    publisher: "Publisher 3",
    developer: "Developer 3",
    platform: "Platform 3",  
},
  {
    id: 4,
    title: "Game4",
    rating: 1.5,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 4",
    publisher: "Publisher 4",
    developer: "Developer 4",
    platform: "Platform 4",  
},
  {
    id: 5,
    title: "Game5",
    rating: 1.3,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 5",
    publisher: "Publisher 5",
    developer: "Developer 5",
    platform: "Platform 5",  
},
  {
    id: 6,
    title: "Game6",
    rating: 10.0,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 6",
    publisher: "Publisher 6",
    developer: "Developer 6",
    platform: "Platform 6",  
},
  {
    id: 7,
    title: "Game7",
    rating: 5.3,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 7",
    publisher: "Publisher 7",
    developer: "Developer 7",
    platform: "Platform 7",  
},
  {
    id: 8,
    title: "Game8",
    rating: 7.3,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 8",
    publisher: "Publisher 8",
    developer: "Developer 8",
    platform: "Platform 8",  
},
  {
    id: 9,
    title: "Game9",
    rating: 2.7,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 9",
    publisher: "Publisher 9",
    developer: "Developer 9",
    platform: "Platform 9",  
},
  {
    id: 10,
    title: "Game10",
    rating: 6.2,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum, mi maximus ornare semper, nunc lorem finibus mauris.",
    genre: "Genre 10",
    publisher: "Publisher 10",
    developer: "Developer 10",
    platform: "Platform 10",  
},
];
