import { StatisticData } from "@/types/statistic";

export const STATISTIC_DATA: StatisticData[] = [
  {
    id: "user1",
    username: "User 1",
    reviewsCount: 3,
    complaintsCount: 0,
    blocksCount: 1,
    unblocksCount: 1,
    lastReviewDate: "2025-03-29",
    lastBlockDate: "2025-03-30",
    lastUnblockDate: "2025-03-26",
    status: "unblocked",
  },
  {
    id: "user2",
    username: "User 2",
    reviewsCount: 2,
    complaintsCount: 2,
    blocksCount: 1,
    unblocksCount: 0,
    lastReviewDate: "2025-03-29",
    lastBlockDate: "2025-03-25",
    lastUnblockDate: null,
    status: "blocked",
  },
  {
    id: "user3",
    username: "User 3",
    reviewsCount: 15,
    complaintsCount: 0,
    blocksCount: 0,
    unblocksCount: 0,
    lastReviewDate: "2025-03-23",
    lastBlockDate: null,
    lastUnblockDate: null,
    status: "unblocked",
  },
  {
    id: "user4",
    username: "User 4",
    reviewsCount: 8,
    complaintsCount: 1,
    blocksCount: 2,
    unblocksCount: 1,
    lastReviewDate: "2025-03-28",
    lastBlockDate: "2025-03-27",
    lastUnblockDate: "2025-03-15",
    status: "blocked",
  },
  {
    id: "user5",
    username: "User 5",
    reviewsCount: 5,
    complaintsCount: 3,
    blocksCount: 0,
    unblocksCount: 0,
    lastReviewDate: "2025-03-20",
    lastBlockDate: null,
    lastUnblockDate: null,
    status: "unblocked",
  },
];
